version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: infra_mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - infra_network
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  redis:
    image: redis:7.2.1
    container_name: infra_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - infra_network
    ports:
      - "127.0.0.1:6379:6379"
    command: redis-server --appendonly yes

networks:
  infra_network:
    driver: bridge
    name: infra_network

volumes:
  mongodb_data:
  redis_data:

